---
layout: documentation
---
:title: Muon.js
:date: 2015-01-05 11:40
:comments: true
:sharing: true
:source-highlighter: pygments
:toc: right
:toc-title: Muon.js
:toclevels: 6

:includedir: .
ifdef::env-doc[]
:includedir: submodules/muonjs/doc
endif::[]

TIP: This document is maintained at https://github.com/muoncore/muon.js Please submit issues at that repository.

## Muon.js

Muon.js takes Muon Node and adds a websockets based transport and discovery. These connect to the
link:/submodules/muonjs-gateway/doc[MuonJS Gateway] service.

This enables Muon to run within the browser and interact with back end services with the full
set of protocols available to server side microservices.

In order to use Muon in the browser, you therefore need to :-

* Set up the MuonJS gateway, connected to the target Muon network.
* Import muon.js into your browser context (either directly, or more likely using npm with webpack or similar)
* Instantiate a Muon object in your browser, which fronts a websocket connection to the gateway.

### Setup

See the MuonJS Gateway documentation for setting this up.
